// Generated by scripts/sync-hokonavi-dp.mjs. Do not edit manually.
export const HOKONAVI_DP_MANIFEST = {
  "source": "hokonavi-dp",
  "sourceLabel": "ほこナビ DP",
  "generatedAt": "2026-06-02T01:24:12.620Z",
  "datasetCount": 28,
  "datasets": [
    {
      "id": "nwd_aizuwakamatsu",
      "title": "歩行空間ネットワークデータ（会津若松市）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2018-06-20",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_aizuwakamatsu",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/de0ad9e0-ac42-472f-91e7-7df21d1cfaaf/resource/2ff7c65d-ba9f-4801-a43e-ec4cd02883db/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/de0ad9e0-ac42-472f-91e7-7df21d1cfaaf/resource/13e90dd8-70db-4392-9a5f-9642e034575a/download/link.geojson",
      "bounds": {
        "minLat": 37.484057,
        "maxLat": 37.511215,
        "minLon": 139.914461,
        "maxLon": 139.936303
      },
      "nodeCount": 1203,
      "edgeCount": 2836
    },
    {
      "id": "nwd_akabane_station",
      "title": "歩行空間ネットワークデータ（赤羽駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2026-03-19",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_akabane_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/2a0005b1-cdf2-43b7-81f8-2ce05a987da2/resource/042e7998-34cc-48ed-b23d-b5953898bed2/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/2a0005b1-cdf2-43b7-81f8-2ce05a987da2/resource/55b154d0-ced2-494e-94cb-ff02c623ee79/download/link.geojson",
      "bounds": {
        "minLat": 35.771409,
        "maxLat": 35.788136,
        "minLon": 139.70469,
        "maxLon": 139.726946
      },
      "nodeCount": 3831,
      "edgeCount": 8604
    },
    {
      "id": "nwd_ariake_tennis",
      "title": "歩行空間ネットワークデータ（東京都江東区・有明テニスの森公園周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_ariake_tennis",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/9d7337a4-50d0-4aa8-b221-cc260ad0bf36/resource/aa4ffe84-b066-46da-bb05-3c688b2abdbd/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/9d7337a4-50d0-4aa8-b221-cc260ad0bf36/resource/af52aad1-5e5d-4fcc-b57d-5bbd67df45f5/download/link.geojson",
      "bounds": {
        "minLat": 35.634992,
        "maxLat": 35.654854,
        "minLon": 139.78782,
        "maxLon": 139.803974
      },
      "nodeCount": 731,
      "edgeCount": 1595
    },
    {
      "id": "nwd_chiyoda_chuo",
      "title": "歩行空間ネットワークデータ（皇居外苑、日本武道館を含む千代田区、中央区周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2018-06-20",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_chiyoda_chuo",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/dee0869a-c58f-445e-9a8c-4d3fc31be344/resource/727a6bcd-0716-4d9b-8f4b-bb7ca71ae691/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/dee0869a-c58f-445e-9a8c-4d3fc31be344/resource/1ced54f1-ebba-4b91-a6cf-f80a965719ad/download/link.geojson",
      "bounds": {
        "minLat": 35.674799,
        "maxLat": 35.696173,
        "minLon": 139.743654,
        "maxLon": 139.774823
      },
      "nodeCount": 1335,
      "edgeCount": 3096
    },
    {
      "id": "nwd_daimon_station",
      "title": "歩行空間ネットワークデータ（港区大門駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-03-29",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_daimon_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/203730b0-45de-4573-a353-a13d7270d076/resource/73ccc910-cb2f-4523-b9f2-8321b714e7aa/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/203730b0-45de-4573-a353-a13d7270d076/resource/075cf314-5266-4a04-a74c-ba7f0636d73e/download/link.geojson",
      "bounds": {
        "minLat": 35.650634,
        "maxLat": 35.663872,
        "minLon": 139.744901,
        "maxLon": 139.762683
      },
      "nodeCount": 1197,
      "edgeCount": 2644
    },
    {
      "id": "nwd_fuchu",
      "title": "歩行空間ネットワークデータ（東京都府中市）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_fuchu",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/07d5f5e3-4ede-44e5-b4ee-4cf978f9bef4/resource/8b09cff6-c59a-43b4-b0c8-f37ae72e5fca/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/07d5f5e3-4ede-44e5-b4ee-4cf978f9bef4/resource/0909bab4-cacd-4735-9ef8-392e24acd926/download/link.geojson",
      "bounds": {
        "minLat": 35.665932,
        "maxLat": 35.678426,
        "minLon": 139.472545,
        "maxLon": 139.485681
      },
      "nodeCount": 1364,
      "edgeCount": 3110
    },
    {
      "id": "nwd_himeji",
      "title": "歩行空間ネットワークデータ（姫路市）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2018-06-20",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_himeji",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/5edb1697-70cc-4b8f-a5e1-aa65631906cd/resource/20cf7944-8b2c-41e1-9295-7b8d8ce97583/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/5edb1697-70cc-4b8f-a5e1-aa65631906cd/resource/5b06b13a-f0de-47c2-a828-982e02972e0d/download/link.geojson",
      "bounds": {
        "minLat": 34.814188,
        "maxLat": 34.837516,
        "minLon": 134.681103,
        "maxLon": 134.700677
      },
      "nodeCount": 1273,
      "edgeCount": 2981
    },
    {
      "id": "nwd_ikebukuro",
      "title": "歩行空間ネットワークデータ（池袋駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-01-28",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_ikebukuro",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/324ba112-3bc0-4b9c-8a36-7d30edf4cf92/resource/f5d9a6e5-fd54-4b77-acd3-6f73e77676ff/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/324ba112-3bc0-4b9c-8a36-7d30edf4cf92/resource/3a384823-0c28-4621-915f-4550537404a6/download/link.geojson",
      "bounds": {
        "minLat": 35.724141,
        "maxLat": 35.733731,
        "minLon": 139.695336,
        "maxLon": 139.722924
      },
      "nodeCount": 1887,
      "edgeCount": 4392
    },
    {
      "id": "nwd_kawasaki_station",
      "title": "歩行空間ネットワークデータ（神奈川県川崎市川崎駅周辺地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-03-07",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_kawasaki_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/35f6ca90-ef8d-44c1-8749-1dd207a50bb8/resource/b8e997b7-f290-4b18-939d-02986f7ca10b/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/35f6ca90-ef8d-44c1-8749-1dd207a50bb8/resource/9a81d096-4323-44f3-9348-d9039de35122/download/link.geojson",
      "bounds": {
        "minLat": 35.523565,
        "maxLat": 35.536082,
        "minLon": 139.691966,
        "maxLon": 139.709872
      },
      "nodeCount": 2288,
      "edgeCount": 5289
    },
    {
      "id": "nwd_kokusai-tenjijo_station",
      "title": "歩行空間ネットワークデータ（東京都江東区・国際展示場周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_kokusai-tenjijo_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/a28dce83-394b-466a-bc00-968a7f51a421/resource/a45f8cd9-8996-4db9-8ba8-0aca09817b57/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/a28dce83-394b-466a-bc00-968a7f51a421/resource/068ef281-5bfd-48f9-9554-a3f8562d559a/download/link.geojson",
      "bounds": {
        "minLat": 35.628767,
        "maxLat": 35.638048,
        "minLon": 139.784235,
        "maxLon": 139.795776
      },
      "nodeCount": 552,
      "edgeCount": 1237
    },
    {
      "id": "nwd_mizonokuchi_station",
      "title": "歩行空間ネットワークデータ（神奈川県川崎市溝口駅周辺地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2022-05-10",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_mizonokuchi_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/1578f0ac-fa88-4f51-8d31-367b2c1eea4d/resource/3f1e940a-e747-48d1-988a-47d0279bb7bb/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/1578f0ac-fa88-4f51-8d31-367b2c1eea4d/resource/d9bbd1c4-ea96-4750-9841-19e87fdffe80/download/link.geojson",
      "bounds": {
        "minLat": 35.592684,
        "maxLat": 35.604734,
        "minLon": 139.605626,
        "maxLon": 139.619231
      },
      "nodeCount": 611,
      "edgeCount": 1350
    },
    {
      "id": "nwd_musashikosugi_station",
      "title": "歩行空間ネットワークデータ（神奈川県川崎市武蔵小杉駅周辺地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2020-03-02",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_musashikosugi_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/f71d308b-0f2d-4ecc-937e-ab7b7e458a55/resource/cfff8c82-a821-4a77-a2fb-4bdf7b393cf5/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/f71d308b-0f2d-4ecc-937e-ab7b7e458a55/resource/ce8e98e4-7101-4411-889a-6e3045717bcb/download/link.geojson",
      "bounds": {
        "minLat": 35.573045,
        "maxLat": 35.582678,
        "minLon": 139.65234,
        "maxLon": 139.66723
      },
      "nodeCount": 1083,
      "edgeCount": 2477
    },
    {
      "id": "nwd_national_stadium",
      "title": "歩行空間ネットワークデータ（東京都新宿区・新国立競技場周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_national_stadium",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/80f20531-e514-4d57-90f1-85be6dcc080e/resource/3c817b8f-aff2-4d8b-991a-3267c1c3955c/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/80f20531-e514-4d57-90f1-85be6dcc080e/resource/43f14c84-9e5e-43a2-adda-69e418b953aa/download/link.geojson",
      "bounds": {
        "minLat": 35.670298,
        "maxLat": 35.679892,
        "minLon": 139.712856,
        "maxLon": 139.721193
      },
      "nodeCount": 436,
      "edgeCount": 914
    },
    {
      "id": "nwd_odaiba-kaihin-koen_station",
      "title": "歩行空間ネットワークデータ（東京都港区・お台場海浜公園周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_odaiba-kaihin-koen_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/e6eb2c0d-f1e7-4901-b154-c0a9c0f53c3d/resource/1f3b7b30-bfb0-420d-9e92-6c1d97862e7c/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/e6eb2c0d-f1e7-4901-b154-c0a9c0f53c3d/resource/5b78e3f4-35e0-4ad8-a272-2b9e9d613b79/download/link.geojson",
      "bounds": {
        "minLat": 35.624039,
        "maxLat": 35.635363,
        "minLon": 139.769004,
        "maxLon": 139.779839
      },
      "nodeCount": 1090,
      "edgeCount": 2431
    },
    {
      "id": "nwd_sabae",
      "title": "歩行空間ネットワークデータ（福井県鯖江市）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_sabae",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/ec2ce99b-8b33-41ad-9892-a3834ed8ed4d/resource/210688af-a1fa-463a-916b-ea11c9d05cc1/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/ec2ce99b-8b33-41ad-9892-a3834ed8ed4d/resource/46a92f0c-e52d-4116-baea-0f36e252d945/download/link.geojson",
      "bounds": {
        "minLat": 35.942944,
        "maxLat": 35.979197,
        "minLon": 136.17555,
        "maxLon": 136.189913
      },
      "nodeCount": 2353,
      "edgeCount": 4984
    },
    {
      "id": "nwd_sendagaya_station",
      "title": "歩行空間ネットワークデータ（渋谷区千駄ヶ谷駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-11-29",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_sendagaya_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/a9c407c3-7823-4cee-9535-769b811289ae/resource/5d687b6f-2edb-4310-9014-521f7224cb1e/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/a9c407c3-7823-4cee-9535-769b811289ae/resource/ec78b0ce-08ed-4c66-b495-9bb7251ef923/download/link.geojson",
      "bounds": {
        "minLat": 35.659504,
        "maxLat": 35.689983,
        "minLon": 139.700961,
        "maxLon": 139.725555
      },
      "nodeCount": 2028,
      "edgeCount": 4360
    },
    {
      "id": "nwd_shibuya_sendagaya_shinjuku",
      "title": "歩行空間ネットワークデータ（東京都渋谷区・渋谷駅、千駄ヶ谷駅周辺／東京都新宿区・新宿駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shibuya_sendagaya_shinjuku",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/eaf1695b-fc4c-41f0-8ff1-3279d0cfa839/resource/7f785b36-48db-4279-a4a5-5140e4dac7c5/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/eaf1695b-fc4c-41f0-8ff1-3279d0cfa839/resource/1d2d13e1-3202-4d0e-bb37-b91e80aab01e/download/link.geojson",
      "bounds": {
        "minLat": 35.653741,
        "maxLat": 35.699618,
        "minLon": 139.686879,
        "maxLon": 139.725555
      },
      "nodeCount": 7155,
      "edgeCount": 15825
    },
    {
      "id": "nwd_shibuya_south",
      "title": "歩行空間ネットワークデータ（渋谷区南部）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2020-03-31",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shibuya_south",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/8401dd6c-a3fb-48f2-8a9d-2955f6320569/resource/491dd1df-a7bc-44c0-97d4-652fd30b2c81/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/8401dd6c-a3fb-48f2-8a9d-2955f6320569/resource/289e1742-5ea6-4e28-a4d5-4838253c0de1/download/link.geojson",
      "bounds": {
        "minLat": 35.653741,
        "maxLat": 35.671678,
        "minLon": 139.689179,
        "maxLon": 139.706828
      },
      "nodeCount": 1641,
      "edgeCount": 3644
    },
    {
      "id": "nwd_shin-kawasaki_kashimada_station",
      "title": "歩行空間ネットワークデータ（神奈川県川崎市新川崎・鹿島田駅周辺地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-02-24",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shin-kawasaki_kashimada_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/47644c78-2384-4a10-9d5d-96cd9dda4283/resource/dd2cb62b-4be4-4bc2-8cec-651632ca3b2d/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/47644c78-2384-4a10-9d5d-96cd9dda4283/resource/80401294-fbe4-49bb-9aa1-e2e66374cd2b/download/link.geojson",
      "bounds": {
        "minLat": 35.545529,
        "maxLat": 35.553974,
        "minLon": 139.668571,
        "maxLon": 139.680545
      },
      "nodeCount": 528,
      "edgeCount": 1130
    },
    {
      "id": "nwd_shin-kiba_station",
      "title": "歩行空間ネットワークデータ（東京都江東区・新木場駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shin-kiba_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/f458b93e-275f-4bee-bb95-840ba4210a09/resource/5547690c-efa3-4100-8044-78e527a5b928/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/f458b93e-275f-4bee-bb95-840ba4210a09/resource/889c10a3-9548-4e57-bdb4-77e7021ebbce/download/link.geojson",
      "bounds": {
        "minLat": 35.644651,
        "maxLat": 35.659059,
        "minLon": 139.809305,
        "maxLon": 139.828454
      },
      "nodeCount": 516,
      "edgeCount": 1124
    },
    {
      "id": "nwd_shin-yokohama",
      "title": "歩行空間ネットワークデータ （新横浜地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2018-10-29",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shin-yokohama",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/f704ee09-6f1e-4492-8dc3-8d98f5505998/resource/aa9b961c-9f08-4336-babd-6e955a7db09b/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/f704ee09-6f1e-4492-8dc3-8d98f5505998/resource/6c41ad49-6700-42c3-87b0-fa561f43a1ba/download/link.geojson",
      "bounds": {
        "minLat": 35.506176,
        "maxLat": 35.518924,
        "minLon": 139.597659,
        "maxLon": 139.621435
      },
      "nodeCount": 1604,
      "edgeCount": 3688
    },
    {
      "id": "nwd_shin-yurigaoka_station",
      "title": "歩行空間ネットワークデータ（神奈川県川崎市新百合ヶ丘駅周辺地区）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2020-03-02",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shin-yurigaoka_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/f9b722c7-13d4-4e6d-833b-97a2d0efb676/resource/443a6a74-96ce-4e04-bca7-5aeccf1aa3ad/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/f9b722c7-13d4-4e6d-833b-97a2d0efb676/resource/7e26160f-a26c-406e-934b-f16582e6a63e/download/link.geojson",
      "bounds": {
        "minLat": 35.60057,
        "maxLat": 35.606021,
        "minLon": 139.500342,
        "maxLon": 139.510482
      },
      "nodeCount": 501,
      "edgeCount": 1129
    },
    {
      "id": "nwd_shinjuku",
      "title": "歩行空間ネットワークデータ（新宿駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2018-10-29",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_shinjuku",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/18bc3f49-51b0-4d90-b0e2-afbdf142de29/resource/462f206a-b231-419d-a8a8-1500760b3a02/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/18bc3f49-51b0-4d90-b0e2-afbdf142de29/resource/5abd6a98-2025-4323-b09d-ed4ea2ddf4aa/download/link.geojson",
      "bounds": {
        "minLat": 35.685667,
        "maxLat": 35.697886,
        "minLon": 139.687188,
        "maxLon": 139.706967
      },
      "nodeCount": 1720,
      "edgeCount": 3723
    },
    {
      "id": "nwd_suminodo_station",
      "title": "歩行空間ネットワークデータ（大阪府大東市・住道駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_suminodo_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/728b6d22-a251-4475-a581-7e8daec400d9/resource/a0a4555b-cbc6-4986-b82a-9e8ff0ecd15d/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/728b6d22-a251-4475-a581-7e8daec400d9/resource/248329bd-92ce-48cd-acd4-f193b596d0b4/download/link.geojson",
      "bounds": {
        "minLat": 34.701987,
        "maxLat": 34.718786,
        "minLon": 135.61151,
        "maxLon": 135.628565
      },
      "nodeCount": 1117,
      "edgeCount": 2505
    },
    {
      "id": "nwd_takamatsu",
      "title": "歩行空間ネットワークデータ（香川県高松市）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_takamatsu",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/5698a32c-f045-4f96-8291-49ee22f1f96d/resource/a2ba9413-1386-42f6-917f-182f3bf68359/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/5698a32c-f045-4f96-8291-49ee22f1f96d/resource/aaae0cdb-1346-42dc-8cf6-959f9b67f039/download/link.geojson",
      "bounds": {
        "minLat": 34.328866,
        "maxLat": 34.357318,
        "minLon": 134.044198,
        "maxLon": 134.061767
      },
      "nodeCount": 2516,
      "edgeCount": 5427
    },
    {
      "id": "nwd_tokyo",
      "title": "歩行空間ネットワークデータ（東京駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-01-23",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_tokyo",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/8ef1f4a8-1848-4491-9a87-ac13b706307c/resource/58536efe-b272-4aa7-a303-2993826ede60/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/8ef1f4a8-1848-4491-9a87-ac13b706307c/resource/00e59f21-4074-4d50-8616-93235fbb9464/download/link.geojson",
      "bounds": {
        "minLat": 35.667673,
        "maxLat": 35.696173,
        "minLon": 139.743654,
        "maxLon": 139.774823
      },
      "nodeCount": 4161,
      "edgeCount": 9894
    },
    {
      "id": "nwd_tokyo-teleport_staion",
      "title": "歩行空間ネットワークデータ（東京都江東区・東京テレポート駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2021-05-26",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_tokyo-teleport_staion",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/74ae3322-7739-40ab-9e89-65cdf3d0658c/resource/41182ea2-e534-40df-9bd7-e8b32c0c8eee/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/74ae3322-7739-40ab-9e89-65cdf3d0658c/resource/dbdde090-9c17-4da0-9188-0fe35e4975b8/download/link.geojson",
      "bounds": {
        "minLat": 35.620432,
        "maxLat": 35.629231,
        "minLon": 139.770838,
        "maxLon": 139.783932
      },
      "nodeCount": 603,
      "edgeCount": 1337
    },
    {
      "id": "nwd_ueno_station",
      "title": "歩行空間ネットワークデータ（台東区上野駅周辺）",
      "sourceLabel": "ほこナビ DP",
      "updatedAt": "2019-03-29",
      "catalogUrl": "https://ckan.hokonavi.go.jp/dataset/nwd_ueno_station",
      "nodeUrl": "https://ckan.hokonavi.go.jp/dataset/2df4cb39-8b2e-4692-97ea-3f6b4132c109/resource/80140abb-8e4b-4083-b6e6-c96e28221bec/download/node.geojson",
      "linkUrl": "https://ckan.hokonavi.go.jp/dataset/2df4cb39-8b2e-4692-97ea-3f6b4132c109/resource/16c453cb-21c0-4e38-8975-0a35803b7edc/download/link.geojson",
      "bounds": {
        "minLat": 35.704766,
        "maxLat": 35.7236,
        "minLon": 139.76767,
        "maxLon": 139.779312
      },
      "nodeCount": 1113,
      "edgeCount": 2466
    }
  ]
} as const;
